apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-monitoring-test-prod-cluster
  region: ap-northeast-2
  version: "1.34"

vpc:
  id: "<VpcId>" # CloudFormation Outputs의 VpcId 입력
  cidr: "10.50.0.0/16"
  subnets:
    public:
      eks-monitoring-test-prod-subnet-public1-ap-northeast-2a:
        id: "<PublicSubnetAId>" # CloudFormation Outputs의 PublicSubnetAId 입력
        cidr: "10.50.1.0/24"
      eks-monitoring-test-prod-subnet-public2-ap-northeast-2c:
        id: "<PublicSubnetCId>" # CloudFormation Outputs의 PublicSubnetCId 입력
        cidr: "10.50.2.0/24"

managedNodeGroups:
  - name: eks-monitoring-test-nodegroup
    instanceType: t3a.medium
    desiredCapacity: 4
    volumeSize: 100
    volumeEncrypted: true
    ssh:
      publicKeyName: eks-monitoring-test-key
    # 노드그룹을 두 서브넷 모두에 배치하여 고가용성 확보
    subnets:
      - "<PublicSubnetAId>"
      - "<PublicSubnetCId>"
    # NodePort 접근을 위해 퍼블릭 IP 할당 유지
    privateNetworking: false
    tags:
      LongTermUse: "Y"
      UserEmail: "jonghyun.baik@cj.net"
      Name: "eks-monitoring-test-nodegroup"
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
        efs: true
        albIngress: true

cloudWatch:
  clusterLogging: {}
