apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-monitoring-test-prod-cluster
  region: ap-northeast-2
  version: "1.34"

vpc:
  id: "vpc-0952fec32cea04558"
  cidr: "10.150.0.0/16"
  subnets:
    public:
      # A존 퍼블릭 서브넷만 정의
      eks-monitoring-test-prod-subnet-public1-ap-northeast-2a:
        id: "subnet-08aa1021322e2f85e"
        cidr: "10.150.0.0/20"

managedNodeGroups:
  - name: eks-monitoring-test-nodegroup
    instanceType: t3a.medium
    desiredCapacity: 4
    volumeSize: 100
    volumeEncrypted: true
    ssh:
      publicKeyName: eks-monitoring-test-key
    subnets:
      - subnet-08aa1021322e2f85e
    privateNetworking: false
    tags:
      LongTermUse: "Y"
      UserEmail: "jonghyun.baik@cj.net"
      Name: "eks-monitoring-test-nodegroup"
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
        efs: true
        albIngress: true

cloudWatch:
  clusterLogging: {}
